### PR TITLE
update enum_point_type and enum_line_type according to the high prior…

### PR DESCRIPTION
**Pull request by WeiweiDuan**
update the enum_point_type and enum_line_type in 02-defs.sql. The updated types are based on the high priority features.

### CODE REVIEW

**Review by davenquinn — CHANGES_REQUESTED** [review]
Hi @WeiweiDuan thanks for your contribution. I'd suggest several things:

Can you link/post a graphical index for your high priority symbols?
The current index of symbols is based on [this resource](https://github.com/UW-Macrostrat/web-components/blob/3de980d53a939991a2025f3d3c9afaa16ec956fa/packages/mapbox-styles/src/layer-helpers/point-features/symbols/README.md); we don't want to remove the identifiers there as they are commonly used. Some are not necessarily in the "high priority" set, but others are just synonyms of the versions you have added.

For example, I am pretty sure `metamorphic` is a synonym of `foliation`.  `bedding` is a synonym of `inclined bedding`, where the actual number value controls the symbol used. It is OK to have multiple synonyms in the list of accepted terms, but if we add the `inclined...` terms we should also add `vertical...` and `horizontal...`. I'd prefer probably for these that the `dip_angle` number was set to the proper value instead of breaking out all symbol permutations in the vocabulary. But both could be an option if it was clearer for TA1 teams (i.e. setting vertical foliation with a dip angle != 90 would be bad data).

Adding `overturned bedding` is important because there is no standard way to capture that with the angles. Also you've misspelled `overturned` 😄 

Overall, just adding things to this set without deleting is IMO the way to go.

**Comment by WeiweiDuan** [comment]
Hi @davenquinn, Thanks a lot for your quick response. I totally agree that we should add things instead of deleting and this list of point feature names should not only have the features with the high priority. 

We set the point feature with high priority according to the Graham's comments in this [doc](https://drive.google.com/file/d/17bLyy-5Xa9wQS7MZZpdksRK8ng1FKeli/view?usp=sharing). We also summarize the features with high priority in the [slides](https://docs.google.com/presentation/d/1dbK-DxhICueXD0GN7_H2ujq2Gwr69dGu0Q1SS55KSX4/edit?usp=sharing). You can find the features we're working on easily in the slides. 

Since the "inclined bedding", "inclined flow banding", and "inclined metamorphic" have the high priority, it's good for us to add them in the point feature names along with the vertical and horizontal ones. What do you think? We can also use "bedding", "flow banding", and "metamorphic", but the dip angle extraction is still needed to be improved. Thanks for your help.

**Comment by davenquinn** [comment]
I think adding all of these types is fine, if the existing ones are kept. Adding the "inclined" notation is fine; it's easy to convert between the two representations.

**Comment by WeiweiDuan** [comment]
Thanks a lot for your help. I sent a new PR, which keeps all types and adds some new types. Thanks.

**Comment by davenquinn** [comment]
Looks great! Thanks for making these changes.

**Pull request merged**
